#:schema node_modules/wrangler/config-schema.json
name = "react-server"
main = "dist/backend/worker.js"
compatibility_date = "2024-06-20"
compatibility_flags = ["nodejs_compat"]

[build]
command = "yarn build-worker"

[site]
bucket = "./dist/frontend"

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["HitCounter"]

[durable_objects]
bindings = [
    { name = "HIT_COUNTER", class_name = "HitCounter" }
]
